#NUMPY OPERATIONS

In [4]:
import numpy as np
a=np.array([1,2,3])
a
a.ndim

1

In [7]:
a=np.array([(1,2,3),(4,5,6)])
a
a.ndim

2

In [8]:
a=np.array([(1,2,3),(4,5,6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a=np.array([(1,2,3),(4,5,6)])
a.itemsize   //size in which data can be stored//

4

In [11]:
a=np.array([(1,2,3),(4,5,6)])
a.size // to get the size of the data//

6

In [12]:
a=np.array([(1,2,3),(4,5,6)])
a.dtype // to count the data type//

dtype('int32')

In [4]:
import numpy as np
a=np.array([(1,2,3),(4,5,6)])
a.shape // to get the column and row size of the data//   

(2, 3)

In [15]:
a=np.array([(1,2,3),(4,5,6)])
a.reshape(3,2)   // to change the column and rows size of the  data//

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
a=np.array([(1,2,3),(4,5,6)])
a // a value have not changed because initially we have define a as (123)(456), does not make any changes after reshape//

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
np.transpose(a) // to get transpose of the given data//

array([[1, 4],
       [2, 5],
       [3, 6]])

In [20]:
a=np.array([(1,2,3),(4,5,6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [28]:
a[1]

2

In [25]:
a=np.array([(1,2,3),(4,5,6)])
a
a[1]

array([4, 5, 6])

In [29]:
a=np.array([(1,2,3),(4,5,6)])
a
a[1,1] 

5

In [30]:
a=np.array([(1,2,3),(4,5,6)])
a
a[0,2] // 0 is x axis and 2 is in y axis //

3

In [31]:
a[0:,2] 

array([3, 6])

In [32]:
a[1:,2]

array([6])

In [49]:
a=np.array([(1,2),(3,4),(5,6),(7,8)])
a
a[0:,1]

array([2, 4, 6, 8])

In [47]:
a[0:2,1]

array([2, 4])

In [39]:
a[0:2,1]

array([2, 4])

In [40]:
a[0:4,1]

array([2, 4, 6, 8])

In [43]:
a[1:,0]

array([3, 5, 7])

In [44]:
a[2:,1]

array([6, 8])

In [48]:
a=np.array([(1,2),(3,4),(5,6),(7,8)])
a
a.ndim

2

In [51]:
a=np.array([(1,2),(3,4),(5,6),(7,8)])
a.min()

1

In [54]:
a=np.array([(1,2),(3,4),(5,6),(7,8)])
a.max()

8

In [55]:
a=np.array([(1,2),(3,4),(5,6),(7,8)])
a.sum()

36

In [56]:
a.sum(axis=0) // addition data of x axis //

array([16, 20])

In [57]:
a.sum(axis=1) // addition data of y axis //

array([ 3,  7, 11, 15])

In [60]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974],
       [2.64575131, 2.82842712]])

In [62]:
type(a)

numpy.ndarray

In [63]:
a=np.array([(1,2),(3,4),(5,6),(7,8)])
b=np.array([(1,2),(3,4),(5,6),(7,8)])
a+b

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [70]:
a+b

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [65]:
a/b

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [66]:
a*b

array([[ 1,  4],
       [ 9, 16],
       [25, 36],
       [49, 64]])

In [67]:
a-b

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

STACKING

In [68]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [69]:
np.hstack((a,b))

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [5, 6, 5, 6],
       [7, 8, 7, 8]])